on: push

name: Flutter

permissions:
  id-token: write
  contents: write
  attestations: write

jobs:
  test-linux:
    runs-on: ubuntu-22.04 # libwebkit2gtk-4.1 is not compatible with flutter
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable" # or: 'beta', 'dev' or 'master'
          architecture: x64 # optional, x64 or arm64
          cache: true
          cache-key: 'flutter-${{ github.job }}-:os:-:channel:-:version:-:arch:-:hash:'
          cache-path: '${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:'
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev libwebkit2gtk-4.0-dev keybinder-3.0
      
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            build
            ~/.gradle
          key: ${{ runner.os }}-flutter-${{ github.job }}-${{ hashFiles('pubspec.lock') }}
      
      - run: flutter --version
      - run: flutter pub get
      # - run: flutter analyze
      - run: flutter test --coverage
      - uses: codecov/codecov-action@v5
        with:
          flags: linux
        env: 
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
